version: '3.8'
services:
  db:
    image: postgres
    container_name: pgdb
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    networks:
      - e-commerce-app
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-api
    command: yarn start:dev
    ports:
      - "${APP_PORT}:9000"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app
      # - /app/node_modules
    env_file:
      - .env
    networks:
      - e-commerce-app
volumes:
  pgdb:
networks:
  e-commerce-app:
